---

name: black

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@master
        with:
          # yamllint disable-line rule:line-length
          args: ". --exclude respondd/respondd-tmpl/lib/respondd_client.py --check --diff"
