name: black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@master
        with:
            args: ". --exclude respondd/respondd-tmpl/lib/respondd_client.py --check --diff"
